spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: smell
    password: 1234

mybatis:
  # mapper 경로 지정
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.smell.moviereview.vo
  configuration:
    map-underscore-to-camel-case: true
